### ISSUE TITLE
Fails to resume after reboot.

### ISSUE THREAD

**Issue by cweimann** [fraenki/f-upgrade#1]
When it reboots it fails to rmdir /tmp/f-upgrade.lock so when the system starts up again it won't resume the upgrade.  I have removed /tmp/f-upgrade.lock twice and run f-upgrade again twice now.  Other than that it seems to work well.   Not sure that this matters but I used it to upgrade from 10.3 to 10.4 on an old test VM.

**Comment by fraenki** [comment]
Thanks for the report. I'll try to reproduce this.

**Comment by fraenki** [comment]
@cweimann, would you test the small patch from https://github.com/fraenki/f-upgrade/pull/2?

I've noticed that my systems were not affected by this, because `clear_tmp_enable="YES"` is enabled in `/etc/rc.conf` on all systems. This option is not a requirement, I was just curious why this issue never hit me in all these years. :)

**Comment by cweimann** [comment]
I'll give that patch a shot.  Also I ought to add clear_tmp_enable="YES" to my systems as well.  I'll test the patch first.

**Comment by cweimann** [comment]
Works.  Thank you.

**Comment by fraenki** [comment]
Thanks for testing again :)
